INSERT INTO ROLES(ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO ROLES(ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (1, 'user', '$2a$10$kFBdXZN9Wq.VMrxa0Q8ZM.tM4tDGK1L7M37jpJLqRfO4LWlvyJPyi');
INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES (2, 'admin', '$2a$10$6o/Dn.GnWwIoW5Hj6vwPp.cXWs4Px.rhHo4t8LlwPTdD5vvWfZWSq');
	
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLES(USER_ID, ROLE_ID) VALUES (2,2);